name: Frontend (Cypress) CI
on:
  push:
    branches: [ "main", "GithubActionsCICD" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Install frontend deps
        run: npm i --legacy-peer-deps
        working-directory: frontend

      - name: Installing root deps
        run: npm i --legacy-peer-deps

      - name: Installing ci/cd tools
        run: npm install -g wait-on nx
        working-directory: frontend

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Serve frontend
        run: npx nx serve frontend
        env:
          NX_CLOUD: false

      - name: Wait for frontend
        run: npx wait-on --timeout 300000 http://localhost:8081

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: frontend
