name: Frontend (Cypress) CI
on:
  push:
    branches: [ "main", "GithubActionsCICD" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install frontend deps
        run: npm install
        working-directory: frontend

      - name: Install backend deps
        run: npm install
        working-directory: backend

      - name: Install CI/CD tools
        run: npm install -g wait-on concurrently
        working-directory: frontend

      - name: Start frontend & backend and run Cypress
        run: |
          npx nx serve frontend &
          npx nx serve backend &
          npx wait-on  http-get://localhost:8081/index.bundle?platform=web http://localhost:3000
          npx cypress run
        env:
          NX_CLOUD: false
          EXPO_PUBLIC_API_URL: http://localhost:3000
          AWS_ACCESS_KEY_ID: ${{ secrets.SAM_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SAM_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
        shell: bash
