name: Postman CI
on:
  push:
    branches: [ "main", "GithubActionsCICD" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_postman_collection:
    runs-on: ubuntu-latest
    steps:
      - name: Clear GitHub Actions Cache
        run: rm -rf ~/.postman
        
      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run Shelter_Smoke_Tests.json
