name: Postman CI
on:
  push:
    branches: [ "main", "GithubActionsCICD" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_postman_collection:
    environment: QA env
    runs-on: ubuntu-latest
    steps:
      - name: Clear GitHub Actions Cache
        run: rm -rf ~/.postman
        
      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run "https://api.getpostman.com/collections/41801404-dc6ad15b-1840-4570-8a9c-55693b6f4f02?apikey=${{ secrets.POSTMAN_API_KEY }}"
