name: Postman (API) CI
on:
  push:
    branches: [ "main", "GithubActionsCICD" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -R
      - run: rm -rf ~/.postman
      - run: npm i --legacy-peer-deps
        working-directory: backend
      - run: npm install -g newman@6 wait-on nx
        working-directory: backend
      - run: |
          curl -s -H "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
            "https://api.getpostman.com/collections/41801404-dc6ad15b-1840-4570-8a9c-55693b6f4f02" \
            -o collection.json
      - run: npx nx serve backend &
        working-directory: backend
        env:
          NX_CLOUD: false
      - run: npx wait-on --timeout 300000 http://localhost:3000
      - run: newman run collection.json

